name: Continuous Integration

on:
  # run this workflow on pull_request activity
  # this includes opening and pushing more commits
  pull_request:
    branches: [ master, 3.24.x, 3.21.x ]

jobs:
  style_check:
    uses: ./.github/workflows/style_check.yml
  bootstrap_policy_run_check:
    needs: style_check
    uses: ./.github/workflows/bootstrap_policy_run_check.yml
  tests:
    needs: bootstrap_policy_run_check
    uses: ./.github/workflows/tests.yml
  valgrind:
    needs: bootstrap_policy_run_check
    uses: ./.github/workflows/valgrind.yml
